### ISSUE TITLE
Issue parsing eslint output

### ISSUE THREAD

**Issue by gabmontes** [feross/snazzy#11]
Using `snazzy` to parse `eslint` output does not seem to honor `eslint` exit code:

``` bash
$ eslint .
...
✖ 3 problems (3 errors, 0 warnings)
$ echo $?
1
$ eslint . | snazzy
...
✖ 3 problems (3 errors, 0 warnings)
$ echo $?
0
```

Using:
- eslint@2.8.0
- snazzy@3.0.1

**Comment by feross** [comment]
That's because `snazzy` is designed to convert from "compact" format, not from "stylish" format. By default, eslint outputs "stylish".

Why do you even need `snazzy` if you're using eslint directly? It doesn't look like it's changing the output at all.

**Comment by OlivierCuyp** [comment]
@feross Could you please re-open this issue.
We use snazzy with **standardx**, the goal is to add warnings on `max-len`, `complexity`, `no-console`, ...

Here is an example, with snazzy:

```sh
> standardx --verbose | snazzy

standardx: Use JavaScript Standard Style (tweaked by standardx) (https://github.com/standard/standardx)

/Users/olivier/Projects/Sagacify/sagastandard-test/index.js
  4:3  error  Unexpected console statement  no-console

✖ 1 problem
npm ERR! code 1
npm ERR! path /Users/olivier/Projects/Sagacify/sagastandard-test
npm ERR! command failed
npm ERR! command sh -c standardx --verbose | snazzy

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/olivier/.npm/_logs/2021-01-21T10_38_18_612Z-debug.lo
```

Without snazzy:

```sh
> standardx --verbose

standardx: Use JavaScript Standard Style (tweaked by standardx) (https://github.com/standard/standardx)
  /Users/olivier/Projects/Sagacify/sagastandard-test/index.js:4:3: Unexpected console statement. (no-console)
```

We would like to differentiate error vs warning so this can be used for local dev and for the CI.

**Comment by OlivierCuyp** [comment]
At the end we used directly eslint extending `eslint-config-standard` with our addition rules and with `eslint -f stylish .` command.
Sorry for the bothering...
