### ISSUE TITLE
snazzy gives incorrect message for "Missing '()' invoking a constructor"

### ISSUE THREAD

**Issue by lukechilds** [feross/snazzy#14]
I've been all over the place with this issue, posting on [standard](https://github.com/feross/standard/issues/725), then [ESLint](https://github.com/eslint/eslint/issues/7792), back to standard and now here 😆 

If I have the code:

```js
const onionoo = new Onionoo()
```

to create a new instance of the `Onionoo` class but leave off the brackets:

```js
const onionoo = new Onionoo
```

`standard` and ESLint give the error `Missing '()' invoking a constructor` but `snazzy` just returns `Missing '`:

```
$ standard
standard: Use JavaScript Standard Style (http://standardjs.com)
standard: Run `standard --fix` to automatically fix some problems.
  /Users/lukechilds/Dev/oss/onionoo-node-client/test/unit.js:14:19: Missing '()' invoking a constructor.

$ snazzy
standard: Use JavaScript Standard Style (http://standardjs.com)
standard: Run `standard --fix` to automatically fix some problems.

/Users/lukechilds/Dev/oss/onionoo-node-client/test/unit.js
  14:19  error  Missing '

✖ 1 problem
```

**Comment by feross** [comment]
@lukechilds Thank you for your persistence and for narrowing down the issue to `snazzy`. The issue was actually with one of our dependents: `standard-json`. PR here: https://github.com/Flet/standard-json/pull/2

Should be all fixed up if you re-install `snazzy` 👍

**Comment by lukechilds** [comment]
@feross Yep, all sorted 👍 

Just realised you're the WebTorrent guy, just wanted to thank you for your talk on DHTs, it blew my mind!

**Comment by feross** [comment]
@lukechilds No problem! Glad you enjoyed it 🎸
