### ISSUE TITLE
Have Snazzy output the same exit code as Standard

### ISSUE THREAD

**Issue by chaucerbao** [feross/snazzy#15]
I'm trying to run the linter on a pre-commit script, so I want NPM to halt if there's a lint error. For whatever reason, NPM halts when Standard encounters an error, but not when Snazzy does.

Standard exits with code 1, while Snazzy exits with 255.

Can Snazzy pass thru the same exit code(s) that Standard produces?

**Comment by feross** [comment]
What command are you using for `standard` and also for `snazzy`? Without that, it's really hard to reproduce what you're talking about.

**Comment by feross** [comment]
Nevermind, I figured it out. We're accidentally setting the exit code to -1 (which gets converted to 255) instead of 1.

**Comment by feross** [comment]
Released as 6.0.0
