### ISSUE TITLE
TypeError: chalk.stripColor is not a function

### ISSUE THREAD

**Issue by ghost** [feross/snazzy#20]
Apologies uprfront (I am a newbie). The newest version of snazzy (7.1.0) has caused a breaking change for me.  I get the following error TypeError: chalk.stripColor is not a function. I have no troubles if I fall back to 7.0.0

**Comment by chapa** [comment]
Hey, I had the same error, had to fall back to 7.0.0 as well

**Comment by feross** [comment]
You're right -- my bad. This is fixed in 7.1.1
