### ISSUE TITLE
happy state?

### ISSUE THREAD

**Issue by gabrielcsapo** [feross/snazzy#21]
Any thoughts on having a `good job` state for parsing standard output and seeing no linting errors?

**Comment by feross** [comment]
PR welcome :)

**Comment by gabrielcsapo** [comment]
I was going to discuss what that would like here then open a PR

**Comment by feross** [comment]
On second thought, maybe we shouldn't add this as it violates the Rule of Silence:

> The rule of silence, also referred to as the silence is golden rule, is an important part of the Unix philosophy that states that when a program has nothing surprising, interesting or useful to say, it should say nothing. It means that well-behaved programs should treat their users' attention and concentration as being valuable and thus perform their tasks as unobtrusively as possible. That is, silence in itself is a virtue.

http://www.linfo.org/rule_of_silence.html

**Comment by gabrielcsapo** [comment]
https://github.com/eslint/eslint/issues/3495 Makes sense! Just thought snazzy was innately the visual enhancement of standard and would show a cool “good job!”
