### ISSUE TITLE
Changelog Missing

### ISSUE THREAD

**Issue by Heartnett** [feross/snazzy#28]
**What version of this package are you using?**
The latest stable version.

**What problem do you want to solve?**
Not having to waste time digging in the commit history to see what changed.

**What do you think is the correct solution to this problem?**
Implementing the changelog with the help of a tool such as [standard-version](https://www.npmjs.com/package/standard-version) or [conventional-changelog-writer](https://www.npmjs.com/package/conventional-changelog-writer)

**Are you willing to submit a pull request to implement this change?**
Unfortunately not.

**Comment by feross** [comment]
Thanks for the suggestion, but I don't have time to do this and it's a tradeoff. I'd rather get out releases and address my inbox with 1300+ GitHub notifications. Something has to give.
