### ISSUE TITLE
Not all errors are displayed when piping linter output into snazzy

### ISSUE THREAD

**Issue by galenandrew** [feross/snazzy#6]
Not sure if this is an issue with `standard` or `snazzy`, but…
- When running `standard --verbose | snazzy`, not all errors/problems are displayed.
- When running `snazzy`, all errors are returned (see screenshot)

Running version 5.4.1 on both `standard` and `snazzy`

![screen shot 2016-01-13 at 10 03 24 am](https://cloud.githubusercontent.com/assets/796368/12299681/72b3e1c4-b9dd-11e5-8560-9ff92d857fe9.png)

**Comment by feross** [comment]
Can you check the version of node.js you're using? `node --version` I've seen this issue once before when someone was using a really old version. Cheers!

**Comment by galenandrew** [comment]
Thanks for the tip @feross! I recently upgraded my node version to the latest LTS and can't seem to reproduce it. Seems like that must have been it!!
