### ISSUE TITLE
Issue with solarized-dark

### ISSUE THREAD

**Issue by mrozbarry** [feross/snazzy#9]
This is probably more of an issue with solarized than snazzy, but with solarized-dark, the line numbers and other important information are the same colour as the background, so text needs to be highlighted to see what the information actually is.

**Comment by feross** [comment]
Don't know how we can detect your terminal theme and fix this. If you have ideas, PR welcome.

**Comment by greghaygood** [comment]
eslint had this problem and fixed it this way:

https://github.com/eslint/eslint/commit/a1840e79f46657dff1a24ee20cecf31379a976ff

I tested the change on my local and it works with my dark-colored terminal background. Not sure if it's the right generic fix for everyone else, though.

**Comment by feross** [comment]
Cool, thanks for the link @greghaygood !

**Comment by feross** [comment]
Fix released as 4.0.1.
